#!/bin/bash
set -eu

declare -gar apps=(
curl
diffuse
firefox
fonts-powerline
git
gnome-tweak-tool
libcanberra-gtk-module
libcanberra-gtk3-module
net-tools
openconnect
openssh-client
openssh-server
picocom
powerline
python3
python3-pip
tmux
vim
virtualenv
xclip
)

echo "Installing apps: ${apps[@]}"
apt-get update && apt-get install --yes "${apps[@]}"

echo "Installing vscode..."
snap install --classic code
