#!/bin/bash
set -u

declare -gar apps=(
curl
diffuse
firefox
git
libcanberra-gtk-module
libcanberra-gtk3-module
net-tools
openconnect
openssh-client
openssh-server
tmux
vim
virtualenv
xclip
)

echo "Installing apps: ${apps[@]}"
apt-get update && apt-get install --yes "${apps[@]}"
